coflow_write_json_file <- function(path, payload) {
  if (!requireNamespace("jsonlite", quietly = TRUE)) {
    stop("jsonlite is required for coflow JSON artifacts")
  }
  dir.create(dirname(path), recursive = TRUE, showWarnings = FALSE)
  jsonlite::write_json(payload, path = path, auto_unbox = TRUE, pretty = TRUE)
}

coflow_empty_shortlist_rows <- function() {
  data.frame(
    target = character(),
    mode = character(),
    rank = integer(),
    candidate = character(),
    score = double(),
    sig_share = double(),
    coint_share = double(),
    n_windows = integer(),
    selected_for_contract = logical(),
    stringsAsFactors = FALSE
  )
}

coflow_collect_shortlist_rows <- function(blocks, top_n = 5L) {
  rows <- list()
  idx <- 1L

  for (blk in blocks) {
    target <- as.character(blk$target)
    if (!is.list(blk$rankings) || length(blk$rankings) == 0L) next

    for (mode in names(blk$rankings)) {
      rk <- blk$rankings[[mode]]
      if (!is.data.frame(rk) || nrow(rk) == 0L || !"candidate" %in% names(rk)) next

      for (i in seq_len(nrow(rk))) {
        row <- rk[i, , drop = FALSE]
        rows[[idx]] <- data.frame(
          target = target,
          mode = as.character(mode),
          rank = as.integer(i),
          candidate = as.character(row$candidate[[1L]]),
          score = suppressWarnings(as.numeric(row$score[[1L]])),
          sig_share = suppressWarnings(as.numeric(row$sig_share[[1L]])),
          coint_share = suppressWarnings(as.numeric(row$coint_share[[1L]])),
          n_windows = suppressWarnings(as.integer(row$n_windows[[1L]])),
          selected_for_contract = FALSE,
          stringsAsFactors = FALSE
        )
        idx <- idx + 1L
      }
    }
  }

  if (length(rows) == 0L) return(coflow_empty_shortlist_rows())
  out <- do.call(rbind, rows)
  out <- out[order(out$target, out$mode, out$rank, out$candidate), , drop = FALSE]
  rownames(out) <- NULL

  top_n <- max(1L, as.integer(top_n))
  for (target in unique(out$target)) {
    idx_target <- which(out$target == target)
    mode_set <- unique(out$mode[idx_target])
    chosen_mode <- if ("positive" %in% mode_set) "positive" else if ("least" %in% mode_set) "least" else sort(mode_set)[[1L]]
    pick <- idx_target[out$mode[idx_target] == chosen_mode & out$rank[idx_target] <= top_n]
    if (length(pick) > 0L) out$selected_for_contract[pick] <- TRUE
  }

  out
}

coflow_target_candidates_from_shortlist <- function(rows) {
  out <- list()
  if (!is.data.frame(rows) || nrow(rows) == 0L) return(out)

  for (target in sort(unique(rows$target))) {
    sel <- unique(as.character(rows$candidate[rows$target == target & rows$selected_for_contract == TRUE]))
    sel <- sort(sel[nzchar(sel)])
    out[[target]] <- sel
  }
  out
}

coflow_write_shortlist_r_map <- function(path, target_candidates) {
  lines <- c(
    "# Auto-generated by coflow-R publication tools",
    "DASS_TARGET_CANDIDATES <- list("
  )

  keys <- names(target_candidates)
  if (length(keys) > 0L) {
    for (i in seq_along(keys)) {
      key <- keys[[i]]
      vals <- target_candidates[[key]]
      vals_text <- if (length(vals) == 0L) "character()" else paste(sprintf("\"%s\"", vals), collapse = ", ")
      suffix <- if (i < length(keys)) "," else ""
      lines <- c(lines, sprintf("  %s = c(%s)%s", key, vals_text, suffix))
    }
  }
  lines <- c(lines, ")", "")
  writeLines(lines, con = path, useBytes = TRUE)
}

coflow_export_shortlist <- function(cfg, window_size, blocks) {
  if (!isTRUE(cfg$SHORTLIST_EXPORT_ENABLED)) {
    return(list(
      enabled = FALSE,
      status = "skipped",
      shortlist_csv = "",
      shortlist_json = "",
      shortlist_r_map = "",
      n_rows = 0L,
      n_targets = 0L
    ))
  }

  rows <- coflow_collect_shortlist_rows(blocks, top_n = cfg$SHORTLIST_TOP_N)
  target_candidates <- coflow_target_candidates_from_shortlist(rows)

  stem <- sprintf("%s_rw%d_shortlist", cfg$CONFIG_SLUG, as.integer(window_size))
  csv_path <- file.path(cfg$SHORTLIST_DIR, paste0(stem, ".csv"))
  json_path <- file.path(cfg$SHORTLIST_DIR, paste0(stem, ".json"))
  r_map_path <- file.path(cfg$SHORTLIST_DIR, paste0(stem, ".R"))

  dir.create(cfg$SHORTLIST_DIR, recursive = TRUE, showWarnings = FALSE)
  utils::write.csv(rows, csv_path, row.names = FALSE)
  coflow_write_shortlist_r_map(r_map_path, target_candidates)

  payload <- list(
    generated_at_utc = format(Sys.time(), tz = "UTC", usetz = TRUE),
    config_slug = cfg$CONFIG_SLUG,
    window_size = as.integer(window_size),
    top_n = as.integer(cfg$SHORTLIST_TOP_N),
    n_rows = as.integer(nrow(rows)),
    n_targets = as.integer(length(target_candidates)),
    shortlist_csv = csv_path,
    shortlist_r_map = r_map_path,
    target_candidates = target_candidates
  )
  coflow_write_json_file(json_path, payload)

  list(
    enabled = TRUE,
    status = "ok",
    shortlist_csv = csv_path,
    shortlist_json = json_path,
    shortlist_r_map = r_map_path,
    n_rows = as.integer(nrow(rows)),
    n_targets = as.integer(length(target_candidates))
  )
}

coflow_scan_summary_sections <- function(summary_text) {
  txt <- as.character(summary_text)
  list(
    has_header = any(grepl("^# CoFlow-R Summary", txt)),
    has_target_sections = any(grepl("^## Target:", txt)),
    has_mode_sections = any(grepl("^### Mode:", txt)),
    has_scoring_profile = any(grepl("- Scoring profile:", txt, fixed = TRUE)),
    has_lag_selection = any(grepl("- Lag selection criterion:", txt, fixed = TRUE))
  )
}

coflow_run_publication_gate <- function(cfg, window_size, summary_path, shortlist_info = NULL, analytics_info = NULL) {
  if (!isTRUE(cfg$PUBLICATION_GATE_ENABLED)) {
    return(list(
      enabled = FALSE,
      status = "skipped",
      report_json = "",
      errors = character(),
      warnings = character()
    ))
  }

  errors <- character()
  warnings <- character()

  if (!file.exists(summary_path)) {
    errors <- c(errors, sprintf("Summary markdown missing: %s", summary_path))
    summary_text <- character()
  } else {
    summary_text <- readLines(summary_path, warn = FALSE)
    sections <- coflow_scan_summary_sections(summary_text)
    if (!isTRUE(sections$has_header)) errors <- c(errors, "Missing summary header")
    if (!isTRUE(sections$has_scoring_profile)) errors <- c(errors, "Missing scoring profile section")
    if (!isTRUE(sections$has_lag_selection)) errors <- c(errors, "Missing lag selection section")
    if (!isTRUE(sections$has_target_sections)) warnings <- c(warnings, "No target sections present")
    if (!isTRUE(sections$has_mode_sections)) warnings <- c(warnings, "No mode sections present")
  }

  if (isTRUE(cfg$SHORTLIST_EXPORT_ENABLED)) {
    if (is.null(shortlist_info) || !nzchar(as.character(shortlist_info$shortlist_json)) || !file.exists(as.character(shortlist_info$shortlist_json))) {
      warnings <- c(warnings, "Shortlist export is enabled but shortlist JSON is missing")
    }
  }

  if (isTRUE(cfg$ADVANCED_ANALYTICS_ENABLED)) {
    if (is.null(analytics_info) || !nzchar(as.character(analytics_info$report_json)) || !file.exists(as.character(analytics_info$report_json))) {
      warnings <- c(warnings, "Advanced analytics is enabled but analytics report is missing")
    }
  }

  if (isTRUE(cfg$PUBLICATION_GATE_STRICT) && length(warnings) > 0L) {
    errors <- c(errors, sprintf("Strict gate mode promoted %d warning(s) to failure", length(warnings)))
  }

  status <- if (length(errors) > 0L) "fail" else if (length(warnings) > 0L) "warn" else "pass"
  report <- list(
    status = status,
    config_slug = cfg$CONFIG_SLUG,
    window_size = as.integer(window_size),
    summary_file = as.character(summary_path),
    shortlist_json = if (!is.null(shortlist_info)) as.character(shortlist_info$shortlist_json) else "",
    analytics_report_json = if (!is.null(analytics_info)) as.character(analytics_info$report_json) else "",
    strict_mode = isTRUE(cfg$PUBLICATION_GATE_STRICT),
    error_count = as.integer(length(errors)),
    warning_count = as.integer(length(warnings)),
    errors = unname(errors),
    warnings = unname(warnings),
    checked_at_utc = format(Sys.time(), tz = "UTC", usetz = TRUE)
  )

  report_path <- file.path(cfg$PUBLICATION_DIR, sprintf("%s_rw%d_publication_gate.json", cfg$CONFIG_SLUG, as.integer(window_size)))
  coflow_write_json_file(report_path, report)

  if (status == "fail" && isTRUE(cfg$PUBLICATION_GATE_FAIL_ON_FAIL)) {
    stop(sprintf("Publication gate failed for window %d", as.integer(window_size)))
  }

  c(report, list(enabled = TRUE, report_json = report_path))
}
